# Generated by Django 4.2.14 on 2024-08-09 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_player_is_white'),
        ('pieces', '0002_gameplay_is_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplay',
            name='black_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black', to='accounts.player'),
        ),
        migrations.AlterField(
            model_name='gameplay',
            name='white_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='white', to='accounts.player'),
        ),
    ]
