# Generated by Django 4.2.14 on 2024-08-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0003_alter_gameplay_black_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplay',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
