# Generated by Django 4.2.14 on 2024-08-31 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0004_gameplay_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserQueue',
        ),
    ]
