# Generated by Django 4.2.14 on 2024-09-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0005_delete_userqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplay',
            name='black_player_in_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameplay',
            name='black_player_is_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameplay',
            name='white_player_in_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameplay',
            name='white_player_is_winner',
            field=models.BooleanField(default=False),
        ),
    ]
