# Generated by Django 4.2.14 on 2024-08-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_white',
            field=models.BooleanField(default=True),
        ),
    ]
