# Generated by Django 4.2.14 on 2024-08-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_player_is_white'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='is_white',
            field=models.BooleanField(default=False),
        ),
    ]
