# Generated by Django 4.2.14 on 2024-08-31 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_player_is_white'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_white',
        ),
    ]
