# Generated by Django 4.2.14 on 2024-09-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_player_is_white'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='in_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
    ]
