# Generated by Django 4.2.14 on 2024-09-05 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_player_in_check_player_is_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='in_check',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_winner',
        ),
    ]
